import Head from "next/head";
import Draggable from "react-draggable";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Draggable
          handle=".handle"
          defaultPosition={{ x: 0, y: 0 }}
          position={null}
          grid={[50, 50]}
          scale={1}
        >
          <div className={`${styles.drag} handle`}>drag and drop</div>
        </Draggable>
      </main>
    </div>
  );
}
